In [1]:
import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt

In [2]:
df_news = pd.read_csv("data/raw/financial_news.csv")
df_news.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/financial_news.csv'

In [3]:
import os
os.getcwd()

'c:\\Users\\Acer\\Documents\\news-sentiment-analysis\\notebooks'

In [4]:
df_news = pd.read_csv("../data/raw/financial_news.csv")

In [5]:
df_stock = pd.read_csv("../data/raw/sample_stocks.csv")

In [6]:
import os
print(os.listdir("../data/raw"))

['.ipynb_checkpoints', 'financial_news.csv', 'sample_stock2.csv', 'sample_stocks.csv']

In [7]:
df_news = pd.read_csv("../data/raw/financial_news.csv")
df_stock = pd.read_csv("../data/raw/sample_stocks.csv")

In [8]:
import pandas as pd

df_news = pd.read_csv("../data/raw/financial_news.csv")
df_news.head()

                                   headline sentiment
0       Stock market rises after tech rally  positive
1     Company reports huge quarterly losses  negative
2  Investors remain cautious amid inflation   neutral
3      Bank stocks surge on strong earnings  positive
4        Oil prices fall due to weak demand  negative

In [9]:
mapping = {
    "positive": 1,
    "neutral": 0,
    "negative": -1
}

df_news["sentiment_score"] = df_news["sentiment"].map(mapping)
df_news.head()

                                   headline sentiment  sentiment_score
0       Stock market rises after tech rally  positive                1
1     Company reports huge quarterly losses  negative               -1
2  Investors remain cautious amid inflation   neutral                0
3      Bank stocks surge on strong earnings  positive                1
4        Oil prices fall due to weak demand  negative               -1